name: Lovable Agent — ChatGPT post-push fixes

on:
  push:
    branches: [ main ]   # ↙ 필요 시 러버블이 푸시하는 브랜치명으로 바꾸세요
  workflow_dispatch:     # 수동 실행도 허용

jobs:
  auto_fix:
    if: ${{ github.actor != 'github-actions[bot]' }}   # 에이전트가 만든 커밋에는 재실행 방지
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 변경사항 푸시 권한
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2   # 직전 커밋과의 diff를 구하기 위해

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install --upgrade openai

      - name: Run fixer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL: ${{ vars.OPENAI_MODEL }}         # (선택) 리포지토리 Variables에 설정
          FILE_GLOBS: ${{ vars.FILE_GLOBS }}             # (선택) 예: 'src/**/*.ts,src/**/*.tsx'
          MAX_FILES: ${{ vars.MAX_FILES }}               # (선택) 기본 10
          MAX_CHARS_PER_FILE: ${{ vars.MAX_CHARS_PER_FILE }} # (선택) 기본 50000
        run: |
          python .github/scripts/chatgpt_fix.py

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add -A
          git commit -m "chore(agent): small fixes via ChatGPT" || exit 0
          git push
